// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lezzercringe/avito-test-assignment/internal/usecases (interfaces: teamRepository,prRepository,userRepository)
//
// Generated by this command:
//
//	mockgen -typed -destination ../../mocks/repositories.go -package mocks . teamRepository,prRepository,userRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	prs "github.com/lezzercringe/avito-test-assignment/internal/prs"
	teams "github.com/lezzercringe/avito-test-assignment/internal/teams"
	usecases "github.com/lezzercringe/avito-test-assignment/internal/usecases"
	users "github.com/lezzercringe/avito-test-assignment/internal/users"
	gomock "go.uber.org/mock/gomock"
)

// MockteamRepository is a mock of teamRepository interface.
type MockteamRepository struct {
	ctrl     *gomock.Controller
	recorder *MockteamRepositoryMockRecorder
	isgomock struct{}
}

// MockteamRepositoryMockRecorder is the mock recorder for MockteamRepository.
type MockteamRepositoryMockRecorder struct {
	mock *MockteamRepository
}

// NewMockteamRepository creates a new mock instance.
func NewMockteamRepository(ctrl *gomock.Controller) *MockteamRepository {
	mock := &MockteamRepository{ctrl: ctrl}
	mock.recorder = &MockteamRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamRepository) EXPECT() *MockteamRepositoryMockRecorder {
	return m.recorder
}

// GetByMemberID mocks base method.
func (m *MockteamRepository) GetByMemberID(ctx context.Context, memberID string) (*teams.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByMemberID", ctx, memberID)
	ret0, _ := ret[0].(*teams.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByMemberID indicates an expected call of GetByMemberID.
func (mr *MockteamRepositoryMockRecorder) GetByMemberID(ctx, memberID any) *MockteamRepositoryGetByMemberIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByMemberID", reflect.TypeOf((*MockteamRepository)(nil).GetByMemberID), ctx, memberID)
	return &MockteamRepositoryGetByMemberIDCall{Call: call}
}

// MockteamRepositoryGetByMemberIDCall wrap *gomock.Call
type MockteamRepositoryGetByMemberIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockteamRepositoryGetByMemberIDCall) Return(arg0 *teams.Team, arg1 error) *MockteamRepositoryGetByMemberIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockteamRepositoryGetByMemberIDCall) Do(f func(context.Context, string) (*teams.Team, error)) *MockteamRepositoryGetByMemberIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockteamRepositoryGetByMemberIDCall) DoAndReturn(f func(context.Context, string) (*teams.Team, error)) *MockteamRepositoryGetByMemberIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByName mocks base method.
func (m *MockteamRepository) GetByName(ctx context.Context, name string) (*teams.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*teams.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockteamRepositoryMockRecorder) GetByName(ctx, name any) *MockteamRepositoryGetByNameCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockteamRepository)(nil).GetByName), ctx, name)
	return &MockteamRepositoryGetByNameCall{Call: call}
}

// MockteamRepositoryGetByNameCall wrap *gomock.Call
type MockteamRepositoryGetByNameCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockteamRepositoryGetByNameCall) Return(arg0 *teams.Team, arg1 error) *MockteamRepositoryGetByNameCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockteamRepositoryGetByNameCall) Do(f func(context.Context, string) (*teams.Team, error)) *MockteamRepositoryGetByNameCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockteamRepositoryGetByNameCall) DoAndReturn(f func(context.Context, string) (*teams.Team, error)) *MockteamRepositoryGetByNameCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetManyByNames mocks base method.
func (m *MockteamRepository) GetManyByNames(ctx context.Context, names ...string) (map[string]teams.Team, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range names {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetManyByNames", varargs...)
	ret0, _ := ret[0].(map[string]teams.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyByNames indicates an expected call of GetManyByNames.
func (mr *MockteamRepositoryMockRecorder) GetManyByNames(ctx any, names ...any) *MockteamRepositoryGetManyByNamesCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, names...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyByNames", reflect.TypeOf((*MockteamRepository)(nil).GetManyByNames), varargs...)
	return &MockteamRepositoryGetManyByNamesCall{Call: call}
}

// MockteamRepositoryGetManyByNamesCall wrap *gomock.Call
type MockteamRepositoryGetManyByNamesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockteamRepositoryGetManyByNamesCall) Return(arg0 map[string]teams.Team, arg1 error) *MockteamRepositoryGetManyByNamesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockteamRepositoryGetManyByNamesCall) Do(f func(context.Context, ...string) (map[string]teams.Team, error)) *MockteamRepositoryGetManyByNamesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockteamRepositoryGetManyByNamesCall) DoAndReturn(f func(context.Context, ...string) (map[string]teams.Team, error)) *MockteamRepositoryGetManyByNamesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockteamRepository) Save(ctx context.Context, t *teams.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockteamRepositoryMockRecorder) Save(ctx, t any) *MockteamRepositorySaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockteamRepository)(nil).Save), ctx, t)
	return &MockteamRepositorySaveCall{Call: call}
}

// MockteamRepositorySaveCall wrap *gomock.Call
type MockteamRepositorySaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockteamRepositorySaveCall) Return(arg0 error) *MockteamRepositorySaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockteamRepositorySaveCall) Do(f func(context.Context, *teams.Team) error) *MockteamRepositorySaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockteamRepositorySaveCall) DoAndReturn(f func(context.Context, *teams.Team) error) *MockteamRepositorySaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockprRepository is a mock of prRepository interface.
type MockprRepository struct {
	ctrl     *gomock.Controller
	recorder *MockprRepositoryMockRecorder
	isgomock struct{}
}

// MockprRepositoryMockRecorder is the mock recorder for MockprRepository.
type MockprRepositoryMockRecorder struct {
	mock *MockprRepository
}

// NewMockprRepository creates a new mock instance.
func NewMockprRepository(ctrl *gomock.Controller) *MockprRepository {
	mock := &MockprRepository{ctrl: ctrl}
	mock.recorder = &MockprRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprRepository) EXPECT() *MockprRepositoryMockRecorder {
	return m.recorder
}

// GetAllUnmergedWithAnyOfReviewers mocks base method.
func (m *MockprRepository) GetAllUnmergedWithAnyOfReviewers(ctx context.Context, reviewerIDs ...string) ([]*usecases.PRWithMatchedReviewers, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range reviewerIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetAllUnmergedWithAnyOfReviewers", varargs...)
	ret0, _ := ret[0].([]*usecases.PRWithMatchedReviewers)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUnmergedWithAnyOfReviewers indicates an expected call of GetAllUnmergedWithAnyOfReviewers.
func (mr *MockprRepositoryMockRecorder) GetAllUnmergedWithAnyOfReviewers(ctx any, reviewerIDs ...any) *MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, reviewerIDs...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUnmergedWithAnyOfReviewers", reflect.TypeOf((*MockprRepository)(nil).GetAllUnmergedWithAnyOfReviewers), varargs...)
	return &MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall{Call: call}
}

// MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall wrap *gomock.Call
type MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall) Return(arg0 []*usecases.PRWithMatchedReviewers, arg1 error) *MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall) Do(f func(context.Context, ...string) ([]*usecases.PRWithMatchedReviewers, error)) *MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall) DoAndReturn(f func(context.Context, ...string) ([]*usecases.PRWithMatchedReviewers, error)) *MockprRepositoryGetAllUnmergedWithAnyOfReviewersCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetByID mocks base method.
func (m *MockprRepository) GetByID(ctx context.Context, id string) (*prs.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*prs.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockprRepositoryMockRecorder) GetByID(ctx, id any) *MockprRepositoryGetByIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockprRepository)(nil).GetByID), ctx, id)
	return &MockprRepositoryGetByIDCall{Call: call}
}

// MockprRepositoryGetByIDCall wrap *gomock.Call
type MockprRepositoryGetByIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockprRepositoryGetByIDCall) Return(arg0 *prs.PullRequest, arg1 error) *MockprRepositoryGetByIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockprRepositoryGetByIDCall) Do(f func(context.Context, string) (*prs.PullRequest, error)) *MockprRepositoryGetByIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockprRepositoryGetByIDCall) DoAndReturn(f func(context.Context, string) (*prs.PullRequest, error)) *MockprRepositoryGetByIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetManyByReviewerID mocks base method.
func (m *MockprRepository) GetManyByReviewerID(ctx context.Context, reviewerID string) ([]*prs.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetManyByReviewerID", ctx, reviewerID)
	ret0, _ := ret[0].([]*prs.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetManyByReviewerID indicates an expected call of GetManyByReviewerID.
func (mr *MockprRepositoryMockRecorder) GetManyByReviewerID(ctx, reviewerID any) *MockprRepositoryGetManyByReviewerIDCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetManyByReviewerID", reflect.TypeOf((*MockprRepository)(nil).GetManyByReviewerID), ctx, reviewerID)
	return &MockprRepositoryGetManyByReviewerIDCall{Call: call}
}

// MockprRepositoryGetManyByReviewerIDCall wrap *gomock.Call
type MockprRepositoryGetManyByReviewerIDCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockprRepositoryGetManyByReviewerIDCall) Return(arg0 []*prs.PullRequest, arg1 error) *MockprRepositoryGetManyByReviewerIDCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockprRepositoryGetManyByReviewerIDCall) Do(f func(context.Context, string) ([]*prs.PullRequest, error)) *MockprRepositoryGetManyByReviewerIDCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockprRepositoryGetManyByReviewerIDCall) DoAndReturn(f func(context.Context, string) ([]*prs.PullRequest, error)) *MockprRepositoryGetManyByReviewerIDCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockprRepository) Save(ctx context.Context, pr *prs.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockprRepositoryMockRecorder) Save(ctx, pr any) *MockprRepositorySaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockprRepository)(nil).Save), ctx, pr)
	return &MockprRepositorySaveCall{Call: call}
}

// MockprRepositorySaveCall wrap *gomock.Call
type MockprRepositorySaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockprRepositorySaveCall) Return(arg0 error) *MockprRepositorySaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockprRepositorySaveCall) Do(f func(context.Context, *prs.PullRequest) error) *MockprRepositorySaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockprRepositorySaveCall) DoAndReturn(f func(context.Context, *prs.PullRequest) error) *MockprRepositorySaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveMany mocks base method.
func (m *MockprRepository) SaveMany(ctx context.Context, el ...*prs.PullRequest) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range el {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveMany", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMany indicates an expected call of SaveMany.
func (mr *MockprRepositoryMockRecorder) SaveMany(ctx any, el ...any) *MockprRepositorySaveManyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, el...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMany", reflect.TypeOf((*MockprRepository)(nil).SaveMany), varargs...)
	return &MockprRepositorySaveManyCall{Call: call}
}

// MockprRepositorySaveManyCall wrap *gomock.Call
type MockprRepositorySaveManyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockprRepositorySaveManyCall) Return(arg0 error) *MockprRepositorySaveManyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockprRepositorySaveManyCall) Do(f func(context.Context, ...*prs.PullRequest) error) *MockprRepositorySaveManyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockprRepositorySaveManyCall) DoAndReturn(f func(context.Context, ...*prs.PullRequest) error) *MockprRepositorySaveManyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockuserRepository is a mock of userRepository interface.
type MockuserRepository struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepositoryMockRecorder
	isgomock struct{}
}

// MockuserRepositoryMockRecorder is the mock recorder for MockuserRepository.
type MockuserRepositoryMockRecorder struct {
	mock *MockuserRepository
}

// NewMockuserRepository creates a new mock instance.
func NewMockuserRepository(ctrl *gomock.Controller) *MockuserRepository {
	mock := &MockuserRepository{ctrl: ctrl}
	mock.recorder = &MockuserRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepository) EXPECT() *MockuserRepositoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockuserRepository) Get(ctx context.Context, id string) (*users.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockuserRepositoryMockRecorder) Get(ctx, id any) *MockuserRepositoryGetCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockuserRepository)(nil).Get), ctx, id)
	return &MockuserRepositoryGetCall{Call: call}
}

// MockuserRepositoryGetCall wrap *gomock.Call
type MockuserRepositoryGetCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserRepositoryGetCall) Return(arg0 *users.User, arg1 error) *MockuserRepositoryGetCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserRepositoryGetCall) Do(f func(context.Context, string) (*users.User, error)) *MockuserRepositoryGetCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserRepositoryGetCall) DoAndReturn(f func(context.Context, string) (*users.User, error)) *MockuserRepositoryGetCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetMany mocks base method.
func (m *MockuserRepository) GetMany(ctx context.Context, id ...string) ([]*users.User, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range id {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "GetMany", varargs...)
	ret0, _ := ret[0].([]*users.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMany indicates an expected call of GetMany.
func (mr *MockuserRepositoryMockRecorder) GetMany(ctx any, id ...any) *MockuserRepositoryGetManyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, id...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMany", reflect.TypeOf((*MockuserRepository)(nil).GetMany), varargs...)
	return &MockuserRepositoryGetManyCall{Call: call}
}

// MockuserRepositoryGetManyCall wrap *gomock.Call
type MockuserRepositoryGetManyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserRepositoryGetManyCall) Return(arg0 []*users.User, arg1 error) *MockuserRepositoryGetManyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserRepositoryGetManyCall) Do(f func(context.Context, ...string) ([]*users.User, error)) *MockuserRepositoryGetManyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserRepositoryGetManyCall) DoAndReturn(f func(context.Context, ...string) ([]*users.User, error)) *MockuserRepositoryGetManyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Save mocks base method.
func (m *MockuserRepository) Save(ctx context.Context, u *users.User) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, u)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockuserRepositoryMockRecorder) Save(ctx, u any) *MockuserRepositorySaveCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockuserRepository)(nil).Save), ctx, u)
	return &MockuserRepositorySaveCall{Call: call}
}

// MockuserRepositorySaveCall wrap *gomock.Call
type MockuserRepositorySaveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserRepositorySaveCall) Return(arg0 error) *MockuserRepositorySaveCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserRepositorySaveCall) Do(f func(context.Context, *users.User) error) *MockuserRepositorySaveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserRepositorySaveCall) DoAndReturn(f func(context.Context, *users.User) error) *MockuserRepositorySaveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// SaveMany mocks base method.
func (m *MockuserRepository) SaveMany(ctx context.Context, u ...*users.User) error {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range u {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "SaveMany", varargs...)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMany indicates an expected call of SaveMany.
func (mr *MockuserRepositoryMockRecorder) SaveMany(ctx any, u ...any) *MockuserRepositorySaveManyCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, u...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMany", reflect.TypeOf((*MockuserRepository)(nil).SaveMany), varargs...)
	return &MockuserRepositorySaveManyCall{Call: call}
}

// MockuserRepositorySaveManyCall wrap *gomock.Call
type MockuserRepositorySaveManyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserRepositorySaveManyCall) Return(arg0 error) *MockuserRepositorySaveManyCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserRepositorySaveManyCall) Do(f func(context.Context, ...*users.User) error) *MockuserRepositorySaveManyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserRepositorySaveManyCall) DoAndReturn(f func(context.Context, ...*users.User) error) *MockuserRepositorySaveManyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
