// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lezzercringe/avito-test-assignment/internal/usecases (interfaces: ReviewerPicker)
//
// Generated by this command:
//
//	mockgen -typed -destination mocks/reviewer_picker.go -package mocks github.com/lezzercringe/avito-test-assignment/internal/usecases ReviewerPicker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecases "github.com/lezzercringe/avito-test-assignment/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockReviewerPicker is a mock of ReviewerPicker interface.
type MockReviewerPicker struct {
	ctrl     *gomock.Controller
	recorder *MockReviewerPickerMockRecorder
	isgomock struct{}
}

// MockReviewerPickerMockRecorder is the mock recorder for MockReviewerPicker.
type MockReviewerPickerMockRecorder struct {
	mock *MockReviewerPicker
}

// NewMockReviewerPicker creates a new mock instance.
func NewMockReviewerPicker(ctrl *gomock.Controller) *MockReviewerPicker {
	mock := &MockReviewerPicker{ctrl: ctrl}
	mock.recorder = &MockReviewerPickerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReviewerPicker) EXPECT() *MockReviewerPickerMockRecorder {
	return m.recorder
}

// PickReviewersFromTeam mocks base method.
func (m *MockReviewerPicker) PickReviewersFromTeam(ctx context.Context, req usecases.PickReviewersRequest) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PickReviewersFromTeam", ctx, req)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PickReviewersFromTeam indicates an expected call of PickReviewersFromTeam.
func (mr *MockReviewerPickerMockRecorder) PickReviewersFromTeam(ctx, req any) *MockReviewerPickerPickReviewersFromTeamCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PickReviewersFromTeam", reflect.TypeOf((*MockReviewerPicker)(nil).PickReviewersFromTeam), ctx, req)
	return &MockReviewerPickerPickReviewersFromTeamCall{Call: call}
}

// MockReviewerPickerPickReviewersFromTeamCall wrap *gomock.Call
type MockReviewerPickerPickReviewersFromTeamCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockReviewerPickerPickReviewersFromTeamCall) Return(arg0 []string, arg1 error) *MockReviewerPickerPickReviewersFromTeamCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockReviewerPickerPickReviewersFromTeamCall) Do(f func(context.Context, usecases.PickReviewersRequest) ([]string, error)) *MockReviewerPickerPickReviewersFromTeamCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockReviewerPickerPickReviewersFromTeamCall) DoAndReturn(f func(context.Context, usecases.PickReviewersRequest) ([]string, error)) *MockReviewerPickerPickReviewersFromTeamCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
