// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/lezzercringe/avito-test-assignment/internal/usecases (interfaces: TxHandle,TxManager)
//
// Generated by this command:
//
//	mockgen -typed -destination ../../mocks/tx.go -package mocks . TxHandle,TxManager
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	usecases "github.com/lezzercringe/avito-test-assignment/internal/usecases"
	gomock "go.uber.org/mock/gomock"
)

// MockTxHandle is a mock of TxHandle interface.
type MockTxHandle struct {
	ctrl     *gomock.Controller
	recorder *MockTxHandleMockRecorder
	isgomock struct{}
}

// MockTxHandleMockRecorder is the mock recorder for MockTxHandle.
type MockTxHandleMockRecorder struct {
	mock *MockTxHandle
}

// NewMockTxHandle creates a new mock instance.
func NewMockTxHandle(ctrl *gomock.Controller) *MockTxHandle {
	mock := &MockTxHandle{ctrl: ctrl}
	mock.recorder = &MockTxHandleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxHandle) EXPECT() *MockTxHandleMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockTxHandle) Commit(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockTxHandleMockRecorder) Commit(arg0 any) *MockTxHandleCommitCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockTxHandle)(nil).Commit), arg0)
	return &MockTxHandleCommitCall{Call: call}
}

// MockTxHandleCommitCall wrap *gomock.Call
type MockTxHandleCommitCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTxHandleCommitCall) Return(arg0 error) *MockTxHandleCommitCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTxHandleCommitCall) Do(f func(context.Context) error) *MockTxHandleCommitCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTxHandleCommitCall) DoAndReturn(f func(context.Context) error) *MockTxHandleCommitCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Rollback mocks base method.
func (m *MockTxHandle) Rollback(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Rollback", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Rollback indicates an expected call of Rollback.
func (mr *MockTxHandleMockRecorder) Rollback(arg0 any) *MockTxHandleRollbackCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Rollback", reflect.TypeOf((*MockTxHandle)(nil).Rollback), arg0)
	return &MockTxHandleRollbackCall{Call: call}
}

// MockTxHandleRollbackCall wrap *gomock.Call
type MockTxHandleRollbackCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTxHandleRollbackCall) Return(arg0 error) *MockTxHandleRollbackCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTxHandleRollbackCall) Do(f func(context.Context) error) *MockTxHandleRollbackCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTxHandleRollbackCall) DoAndReturn(f func(context.Context) error) *MockTxHandleRollbackCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTxManager is a mock of TxManager interface.
type MockTxManager struct {
	ctrl     *gomock.Controller
	recorder *MockTxManagerMockRecorder
	isgomock struct{}
}

// MockTxManagerMockRecorder is the mock recorder for MockTxManager.
type MockTxManagerMockRecorder struct {
	mock *MockTxManager
}

// NewMockTxManager creates a new mock instance.
func NewMockTxManager(ctrl *gomock.Controller) *MockTxManager {
	mock := &MockTxManager{ctrl: ctrl}
	mock.recorder = &MockTxManagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTxManager) EXPECT() *MockTxManagerMockRecorder {
	return m.recorder
}

// WithTx mocks base method.
func (m *MockTxManager) WithTx(parent context.Context) (context.Context, usecases.TxHandle, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", parent)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(usecases.TxHandle)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTxManagerMockRecorder) WithTx(parent any) *MockTxManagerWithTxCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTxManager)(nil).WithTx), parent)
	return &MockTxManagerWithTxCall{Call: call}
}

// MockTxManagerWithTxCall wrap *gomock.Call
type MockTxManagerWithTxCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTxManagerWithTxCall) Return(arg0 context.Context, arg1 usecases.TxHandle, arg2 error) *MockTxManagerWithTxCall {
	c.Call = c.Call.Return(arg0, arg1, arg2)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTxManagerWithTxCall) Do(f func(context.Context) (context.Context, usecases.TxHandle, error)) *MockTxManagerWithTxCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTxManagerWithTxCall) DoAndReturn(f func(context.Context) (context.Context, usecases.TxHandle, error)) *MockTxManagerWithTxCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
